### ISSUE TITLE
Update the team data

### ISSUE THREAD

**Issue by Im-Madhur-Gupta** [GDSC-IIIT-V/gdsc-iiitv-website#4]
- Update the team data for AY 2022-23.
- Change the team data storage to JSON.

**Comment by Ayush-Khandelwal28** [comment]
I would like to work on the issue.

**Comment by Im-Madhur-Gupta** [comment]
@Ayush-Khandelwal28 GFI.

**Comment by Ayush-Khandelwal28** [comment]
#9
